import fs from 'node:fs';
import path from 'node:path';

// Returns the public URL of a WebP sibling generated by
// scripts/generate-webp.mjs (e.g. "images/foo.png" -> "/images/foo.webp"),
// or null if it doesn't exist. Callers render a plain <img> pointing at the
// original file when this returns null, so a missing/failed WebP (script
// never ran, or skipped this one file) never breaks a page — it just means
// that image ships without the bandwidth savings.
export function webpSrcFor(publicRelativePath) {
  const ext = path.extname(publicRelativePath);
  if (!ext) return null;
  const webpRelative = publicRelativePath.slice(0, -ext.length) + '.webp';
  try {
    const absPath = path.join(process.cwd(), 'public', webpRelative);
    return fs.existsSync(absPath) ? `/${webpRelative.replace(/\\/g, '/')}` : null;
  } catch {
    return null;
  }
}
